[app]
port = "8080"
timeout_seconds = 15

[database]
host = "127.0.0.1"
port = "3306"
driver = "mysql"
user = "goauth"
password = "goauth"
database = "goauth_test"

[tokens]

[tokens.access]
# also available: lifespan_hour, lifespan_day
# all lifetimes are summarized, so you can specify multiple
lifespan_minute = 15
secret = "secret1"

[tokens.refresh]
lifespan_hour = 8790
secret = "secret2"

# External services that goauth uses
[services]
[services.guest]
host = "127.0.0.1"
port = "8081"
path = "/api/register"

[services.login]
host = "127.0.0.1"
port = "8081"
path = "/api/login"
