[database]
host = "127.0.0.1"
port = "3306"
driver = "mysql"
user = "deltaart"
password = "deltaart"
database = "goauth"

[tokens]

[tokens.access]
lifespan_minute = 15
secret = "secret1"

[tokens.refresh]
lifespan_hour = 8790
secret = "secret2"
