[app]
port = "8080"
timeout_seconds = 15

[database]
host = "127.0.0.1"
port = "3306"
driver = "mysql"
user = "someuser"
password = "somepw"
database = "goauth"

[tokens]

[tokens.access]
# also available: lifespan_hour, lifespan_day
# all lifetimes are summarized, so you can specify multiple
lifespan_minute = 15
secret = "FirstSuperMegaSecretKeyThatNoOneKnowsAbout!"

[tokens.refresh]
lifespan_day = 30
secret = "SecondSuperMegaSecretKeyThatNoOneKnowsAbout!"

# External services that goauth uses
[services]

[services.guest]
host = "127.0.0.1"
port = "8081"
path = "/api/guest"

[services.login]
host = "127.0.0.1"
port = "8081"
path = "/api/login"
