openapi: 3.1.1
info:
  title: Simple Golang Authentication service
  description: Authentication service that uses JWT refresh and access tokens to authenticate users
  version: 1.0.0
tags:
  - name: v1
    description: Version 1 of the API
servers:
  - url: "/v1"
paths:
  /health-check:
    get:
      tags:
        - v1
      operationId: healthCheckV1
      description: "Checks if the server is healthy"
      responses:
        '200':
          description: "Server is healthy"

  /login:
    get:
      tags:
        - v1
      operationId: LoginUserV1
      description: "Logins user"
      responses:
        '200':
          description: "User logged in"

  /refresh:
    get:
      tags:
        - v1
      operationId: RefreshTokenV1
      description: "Refreshes JWT refresh token, giving new pair of tokens"
      responses:
        '200':
          description: "Tokens refreshed"

  /auth:
    get:
      tags:
        - v1
      operationId: IsAuthV1
      description: "Checks if user is authenticated and token is valid"
      responses:
        '200':
          description: "User is authenticated, token is still valid"

  /guest:
    post:
      tags:
        - v1
      operationId: GuestRegisterV1
      description: "Asks another service to create guest user and returns pair of tokens" 
      responses:
        '200':
          description: "Guest user created, tokens are returned"
