basePath: /api
definitions:
  controllers.GuestOutput:
    properties:
      access_token:
        example: token
        type: string
      expires_at:
        example: 244534234
        type: integer
      refresh_token:
        example: token
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Simple authentication service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Golang Authentication microservice
  version: "0.01"
paths:
  /auth:
    get:
      description: Check if request token is valid and user is authorized
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Authenticate request
  /guest:
    post:
      consumes:
      - application/json
      description: authorizes user as guest
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.GuestOutput'
      summary: guest authorization
  /health_check:
    get:
      description: do healthcheck
      responses:
        "200":
          description: OK
      summary: healthcheck
swagger: "2.0"
