# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Mysql Setup"
      env:
        DB_DATABASE: goauth_test
        DB_USER: goauth
        DB_PASSWORD: goauth
      run : |
        sudo /etc/init.d/mysql start
        sudo mysql -e "CREATE DATABASE ${{ env.DB_DATABASE }};" -proot
        echo database created!
        sudo mysql -e "CREATE USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED BY '${{ env.DB_PASSWORD }}';" -proot
        echo user created!
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${{ env.DB_USER }}'@'localhost' WITH GRANT OPTION;" -proot
        sudo mysql -e "FLUSH PRIVILEGES;" -proot

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
