# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Build
      run: go build -v ./...

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'goauth_test' # Optional, default value is "test". The specified database which will be create
        mysql user: 'goauth' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'goauth' # Required if "mysql user" exists. The password for the "mysql user"

    - name: Test
      run: go test -v ./...
